[package]
version = "0.1.0.a17" # see: https://github.com/prefix-dev/pixi/issues/2946

[package.build.backend]
name = "pixi-build-python"
version = "0.4.*"

[package.build.config]
ignore-pypi-mapping = false

[package.host-dependencies]
uv = "*"
setuptools = "<82.0.0"

[package.run-dependencies]
setuptools = "<82.0.0"  # needed because pkg_resources is used

[workspace]
preview = ["pixi-build"]
channels = ["conda-forge"]
