[package]
version = "0.1.0.a17" # see: https://github.com/prefix-dev/pixi/issues/2946

[package.build.backend]
name = "pixi-build-python"
version = "0.*"

[package.build.config]
ignore-pypi-mapping = false
extra-args = ["-Ceditable_mode=compat"]

[package.host-dependencies]
uv = "*"

[package.run-dependencies]
setuptools = "<81.0.0"  # needed because pkg_resources is used

[workspace]
preview = ["pixi-build"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]

[dependencies]
fastplotlib = { path = "." }
